apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keepalived-exporter-service-monitor
  labels:
    app: prometheus-operator-keepalived-exporter
    chart: prometheus-keepalived-exporter-v0.1
    release: prometheus-operator
  namespace: kube-system
spec:
  endpoints:
  - port: metrics
    interval: 30s
    honorLabels: true
    relabelings:
    - action: replace
      regex: (.+)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    - action: replace
      regex: (.+)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_node_name
      targetLabel: node
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-keepalived-exporter
      release: prometheus-operator
