apiVersion: v1
kind: Service
metadata:
  name: keepalived-exporter
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus-operator-keepalived-exporter
    chart: prometheus-keepalived-exporter-v0.1
    jobLabel: keepalived-exporter
    release: prometheus-operator
  name: keepalived-exporter
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: prometheus-operator-keepalived-exporter
    release: prometheus-operator
